version: '3.8'

volumes:
  postgres-data-ortografia:
  pgadmin-data:

networks:
  ortografia-network:
    driver: bridge

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - ortografia-network

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: db-ortografia
    image: postgres:15.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data-ortografia:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env
    networks:
      - ortografia-network
  
  pdAdmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=alumno@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-data:/certs/server.cert
      - pgadmin-data:/certs/server.key
      - pgadmin-data:/pgadmin4/servers.json
    networks:
      - ortografia-network

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
